# Maze generation
---

Useable algorithms to generate maze. 
- Kruskal's
- Prim's
- Recursive Backtracking
- Aldouse-Broder
- Glowing Tree
- Hunt-and-Kill
- Wilson's
- Eller's


Sources:
---
https://stackoverflow.com/questions/38502/whats-a-good-algorithm-to-generate-a-maze

## Kruskel's maze gen



First a grid will be generated in the size our maze should be.

The initial maze size gets muliplied by two and added one on top to make sure the gird size is odd.
Following that the grid is filled with ones to indikate walls.

In [2]:
import numpy as np
from numpy.random import shuffle

h = 6
w = 6
H = 2 * h + 1
W = 2 * w + 1


grid = np.empty((H, W), dtype=np.int8)
grid.fill(1)
print(grid)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]]


After the grid is filled we create a forest of trees, that are single edges.
In the grid these trees get marked as zeros to indikate the beginnings of paths.

In [8]:
import numpy as np
from numpy.random import shuffle

h = 6
w = 6
H = 2 * h + 1
W = 2 * w + 1


grid = np.empty((H, W), dtype=np.int8)
grid.fill(1)

forest = []
for row in range(1, H - 1, 2):
    for col in range(1, W - 1, 2):
        forest.append([(row,col)])
        grid[row][col] = 0
print(forest)
print(list(enumerate(forest)))
print(grid)

[[(1, 1)], [(1, 3)], [(1, 5)], [(1, 7)], [(1, 9)], [(1, 11)], [(3, 1)], [(3, 3)], [(3, 5)], [(3, 7)], [(3, 9)], [(3, 11)], [(5, 1)], [(5, 3)], [(5, 5)], [(5, 7)], [(5, 9)], [(5, 11)], [(7, 1)], [(7, 3)], [(7, 5)], [(7, 7)], [(7, 9)], [(7, 11)], [(9, 1)], [(9, 3)], [(9, 5)], [(9, 7)], [(9, 9)], [(9, 11)], [(11, 1)], [(11, 3)], [(11, 5)], [(11, 7)], [(11, 9)], [(11, 11)]]
[(0, [(1, 1)]), (1, [(1, 3)]), (2, [(1, 5)]), (3, [(1, 7)]), (4, [(1, 9)]), (5, [(1, 11)]), (6, [(3, 1)]), (7, [(3, 3)]), (8, [(3, 5)]), (9, [(3, 7)]), (10, [(3, 9)]), (11, [(3, 11)]), (12, [(5, 1)]), (13, [(5, 3)]), (14, [(5, 5)]), (15, [(5, 7)]), (16, [(5, 9)]), (17, [(5, 11)]), (18, [(7, 1)]), (19, [(7, 3)]), (20, [(7, 5)]), (21, [(7, 7)]), (22, [(7, 9)]), (23, [(7, 11)]), (24, [(9, 1)]), (25, [(9, 3)]), (26, [(9, 5)]), (27, [(9, 7)]), (28, [(9, 9)]), (29, [(9, 11)]), (30, [(11, 1)]), (31, [(11, 3)]), (32, [(11, 5)]), (33, [(11, 7)]), (34, [(11, 9)]), (35, [(11, 11)])]
[[1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 0 1

Now a new set of edges will be created. These will be used to add to the trees created in the last step. In the end the edges get shuffeld to randomize the order in which they get picked later on. *Only edges between two trees to the left, right, top and bottom get created no edges are created diagonaly between two trees.

In [5]:
import numpy as np
from numpy.random import shuffle

h = 6
w = 6
H = 2 * h + 1
W = 2 * w + 1


grid = np.empty((H, W), dtype=np.int8)
grid.fill(1)

forest = []
for row in range(1, H - 1, 2):
    for col in range(1, W - 1, 2):
        forest.append([(row,col)])
        grid[row][col] = 0

edges = []
for row in range(1, H - 1, 2):
    for col in range(2, W - 1, 2):
        edges.append((row,col))
for row in range(2, H - 1, 2):
    for col in range(1, W - 1, 2):
        edges.append((row,col))

print(edges)

shuffle(edges)

[(1, 2), (1, 4), (1, 6), (1, 8), (1, 10), (3, 2), (3, 4), (3, 6), (3, 8), (3, 10), (5, 2), (5, 4), (5, 6), (5, 8), (5, 10), (7, 2), (7, 4), (7, 6), (7, 8), (7, 10), (9, 2), (9, 4), (9, 6), (9, 8), (9, 10), (11, 2), (11, 4), (11, 6), (11, 8), (11, 10), (2, 1), (2, 3), (2, 5), (2, 7), (2, 9), (2, 11), (4, 1), (4, 3), (4, 5), (4, 7), (4, 9), (4, 11), (6, 1), (6, 3), (6, 5), (6, 7), (6, 9), (6, 11), (8, 1), (8, 3), (8, 5), (8, 7), (8, 9), (8, 11), (10, 1), (10, 3), (10, 5), (10, 7), (10, 9), (10, 11)]


gets location of tree next to edge in forest with enumerate and removes the tree from forest and adds a new tree to forest that is a combination from the two found trees before.

In [7]:
import numpy as np
from numpy.random import shuffle

h = 6
w = 6
H = 2 * h + 1
W = 2 * w + 1


grid = np.empty((H, W), dtype=np.int8)
grid.fill(1)

forest = []
for row in range(1, H - 1, 2):
    for col in range(1, W - 1, 2):
        forest.append([(row,col)])
        grid[row][col] = 0

edges = []
for row in range(1, H - 1, 2):
    for col in range(2, W - 1, 2):
        edges.append((row,col))
for row in range(2, H - 1, 2):
    for col in range(1, W - 1, 2):
        edges.append((row,col))

shuffle(edges)

while len(forest) > 1:
    ce_row, ce_col = edges[0]
    edges = edges[1:]

    tree1 = -1
    tree2 = -1

    if ce_row % 2 == 0:
        tree1 = sum(
            [
                i if (ce_row + 1, ce_col) in j else 0
                for i,j in enumerate(forest)
            ]
        )
    print(tree1)

15
33
-1
13
-1
-1
6
-1
-1
17
-1
32
12
-1
-1
-1
-1
-1
-1
-1
-1
-1
26
-1
19
10
-1
30
-1
25
-1
-1
-1
28
-1
27
9
34
24
23
31
-1
18
16
11
20
22
-1
8
35
-1
29
-1
7
-1
14
-1
-1
21
-1


IndexError: list index out of range